sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t george7a/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true george7a/docker-react npm run test
